name: Ruby

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build
      - name: Run server
        run: |
          ./gradlew run &

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.1
      - name: Install bundler
        working-directory: ./http_server_spec
        run: gem install bundler:1.17.2

      - name: Install gems
        run: |
          cd http_server_spec
          gem update --system >/dev/null
          bundle install
      - name: Run acceptance tests
        run: |
          cd http_server_spec
          rake test:f1 
          rake test:f2
          pkill -f '.*GradleDaemon.*'





